name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        
    - name: Install dependencies
      run: npm ci

    - name: Create .env file
      run: |
        echo "DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" > .env
        echo "JWT_SECRET=\"${{ secrets.JWT_SECRET }}\"" >> .env
        echo "PORT=3001" >> .env
      
    - name: Generate Prisma Client
      run: npm run db:generate

    - name: Migrate Prisma Client
      run: npm run db:migrate

    - name: Build
      run: npm run build
      
    - name: Create deployment package
      run: |
        zip -r deploy.zip dist node_modules package.json package-lock.json prisma .env
      
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        printf "%s" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem
        ssh-keyscan -v -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
    - name: Deploy to EC2
      run: |
        scp -i ~/.ssh/ec2_key.pem deploy.zip ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/
        ssh -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
          mkdir -p ~/node-ts-express-prisma
          rm -rf ~/node-ts-express-prisma/*
          unzip ~/deploy.zip -d ~/node-ts-express-prisma
          cd ~/node-ts-express-prisma
          pm2 stop node-ts-express-prisma || true
          pm2 start dist/server.js --name node-ts-express-prisma
          pm2 save
        '