name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        
    - name: Install dependencies
      run: npm ci

    - name: Create .env file
      run: |
        echo "DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" > .env
        echo "JWT_SECRET=\"${{ secrets.JWT_SECRET }}\"" >> .env
        echo "PORT=3001" >> .env
      
    - name: Generate Prisma Client
      run: npm run db:generate

    - name: Migrate Prisma Client
      run: npm run db:migrate

    - name: Build
      run: npm run build
      
    - name: Create deployment package
      run: |
        zip -r deploy.zip dist node_modules package.json package-lock.json prisma .env
      
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        printf "%s" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem
        ssh-keyscan -v -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
    - name: Deploy to EC2
      run: |
        scp -i ~/.ssh/ec2_key.pem deploy.zip ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/
        ssh -i ~/.ssh/ec2_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
        set -e

        mkdir -p ~/releases
        TIMESTAMP=$(date +%s)
        RELEASE_DIR=~/releases/$TIMESTAMP

        mkdir -p $RELEASE_DIR
        unzip ~/deploy.zip -d $RELEASE_DIR

        cd $RELEASE_DIR
        pm2 start dist/server.js --name node-ts-express-prisma-temp
        sleep 5

        if ! curl --fail http://localhost:3001/health; then
          echo "❌ Health check failed. Rolling back..."
          pm2 stop node-ts-express-prisma-temp
          pm2 delete node-ts-express-prisma-temp
          exit 1
        fi

        pm2 stop node-ts-express-prisma || true
        ln -sfn $RELEASE_DIR ~/node-ts-express-prisma
        pm2 start ~/node-ts-express-prisma/dist/server.js --name node-ts-express-prisma
        pm2 save
        pm2 delete node-ts-express-prisma-temp
        '