name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Create .env file
      run: |
        echo "DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" > .env
        echo "JWT_SECRET=\"${{ secrets.JWT_SECRET }}\"" >> .env
        echo "PORT=3000" >> .env

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd node-ts-express-prisma || git clone git@github.com-RathodSanjayL:RathodSanjayL/node-ts-express-prisma.git && cd node-ts-express-prisma
            git pull origin main
            pnpm install
            pnpm db:generate
            pnpm build
            pm2 restart node-ts-express-prisma || pm2 start dist/server.js --name node-ts-express-prisma
          EOF